# Generated by Django 4.1 on 2022-08-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='name',
        ),
        migrations.AddField(
            model_name='home',
            name='fname',
            field=models.CharField(default='فامیل', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='lname',
            field=models.CharField(default='اسم', max_length=50),
        ),
    ]
