# Generated by Django 4.1 on 2022-08-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_alter_home_fname_alter_home_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=3)),
                ('customers', models.CharField(max_length=5)),
                ('projects', models.CharField(max_length=5)),
                ('awards', models.CharField(max_length=5)),
            ],
        ),
    ]
