# Generated by Django 4.1 on 2022-08-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(default='test.jpg', upload_to='image'),
        ),
    ]
