# Generated by Django 4.1 on 2022-08-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
