# Generated by Django 4.1 on 2022-08-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_remove_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('tools', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project_address', models.TextField()),
            ],
        ),
    ]
