# Generated by Django 4.1 on 2022-08-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_comment_alter_project_project_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_address',
            new_name='github_address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
