# Generated by Django 4.1 on 2022-08-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0016_rename_contact_message_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='city',
            field=models.CharField(default='ایران', max_length=70),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
    ]
